### ISSUE TITLE
Configure to use GitHub merge queue

### ISSUE THREAD

**Issue by cgrindel** [cgrindel/rules_swift_package_manager#812]
I find that I am spending a non-trivial amount of time merging multiple pull requests. I hope that using GitHub's merge queue will remove some of the shepherding duties.

## Tasks
- [x] cgrindel/rules_swift_package_manager/pull/813
- [x] Check if Renovate config needs to be updated. https://docs.renovatebot.com/key-concepts/automerge/#github-merge-queue
- [ ] Enable the merge queue  in the branch protection rule for `main`.

**Comment by cgrindel** [comment]
I just noticed the following:

>Pull request merge queues are available in any public repository owned by an organization, or in private repositories owned by organizations using GitHub Enterprise Cloud. For more information, see "[GitHub’s plans](https://docs.github.com/en/get-started/learning-about-github/githubs-plans)."

[Managing a merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)

Bummer. I guess that we can't use it here. 😞
